apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "A valid .dockerconfigjson entry required!" .Values.imagePullSecretsDockerconfigjsonBase64 }}